#!/bin/sh

cd ~/Code/solr-shanti-configsets/scripts
AUTH=solradmin:IdskBsk013
UPDATE=https://ss251856-us-east-1-aws.measuredsearch.com/solr/kmassets_dev/update

curl -u $AUTH ${UPDATE}/?commit=true -H "Content-Type: text/xml" -d "<delete><query>schema_version_i:(8 7 6 5 4 3 2 1)</query></delete>"
