#!/bin/sh

ME=$0
CONFNAME="kmterms_predev";
CONFDIR=/Users/ys2n/Code/solr-shanti-configsets/solr6.4.x

echo "ME: $ME"
SCRIPTDIR=`dirname $ME`
echo "SCRIPTDIR: $SCRIPTDIR"

source $SCRIPTDIR/zk-settings.inc

EXEC="$ZK -zkhost $ZKHOSTS -cmd downconfig -confdir $CONFDIR/$CONFNAME -confname $CONFNAME"

echo $EXEC
exec $EXEC
